// Generated by CoffeeScript 1.10.0
import Ember from 'ember';
var PageRoute;

PageRoute = Ember.Route.extend({
  model: function(params) {
    return this.store.find('page', params.page_id);
  },
  setupController: function(controller, page) {
    this._super(controller, page);
    return this.controllerFor('admin.questionnaire.pages').set('currentPage', page);
  },
  renderTemplate: function(controller, model) {
    this._super(controller, model);
    return this.render('page_controls', {
      into: 'admin.questionnaire',
      outlet: 'page_controls'
    });
  }
});

export default PageRoute;
