// Generated by CoffeeScript 1.10.0
import Ember from 'ember';
var IndexRoute;

IndexRoute = Ember.Route.extend({
  redirect: function() {
    return this.transitionTo('questionnaire.pages');
  }
});

export default IndexRoute;
