// Generated by CoffeeScript 1.10.0
import Ember from 'ember';
var PagesRoute;

PagesRoute = Ember.Route.extend({
  model: function() {
    return this.modelFor('questionnaire').get('pages');
  },
  actions: {
    setCurrentPage: function(page) {
      var pageController;
      this.transitionTo('page', page);
      pageController = this.controllerFor('page');
      return Ember.run.schedule('afterRender', pageController, pageController.scrollIntoView);
    }
  }
});

export default PagesRoute;
