// Generated by CoffeeScript 1.10.0
import Ember from 'ember';
var QuestionnaireRoute;

QuestionnaireRoute = Ember.Route.extend({
  model: function(controller) {
    var questionnaireId;
    questionnaireId = jQuery('#questionnaire_edit').data('questionnaire-id');
    return this.store.find('questionnaire', questionnaireId);
  },
  redirect: function(model) {
    //return this.transitionTo('questionnaire.pages', { questionnaire: model });
  }
});

export default QuestionnaireRoute;
