// Generated by CoffeeScript 1.10.0

import Ember from 'ember';
var PageController;

PageController = Ember.Controller.extend({
  questionnaire: null,
  needs: ['questionnaire', 'pages'],
  questionnaireBinding: 'controllers.questionnaire',
  defaultLayoutBinding: 'controllers.pages.defaultLayout',
  isCurrent: (function() {
    return this.get('controllers.pages.currentPage.id') === this.get('id');
  }).property('controllers.pages.currentPage.id', 'id'),
  scrollIntoView: function() {
    var element;
    element = $(".answerpage[data-page-id=" + (this.get('id')) + "]").get(0);
    if (element) {
      return element.scrollIntoViewIfNeeded();
    } else {
      return Ember.run.next(this, this.scrollIntoView);
    }
  },
  actions: {
    addQuestion: function(type, purpose) {
      var question;
      question = this.get('store').createRecord('question', {
        page: this.get('model'),
        type: type,
        purpose: purpose,
        layout: this.get('defaultLayout')
      });
      return question.save().then((function(_this) {
        return function() {
          return _this.get('questions').addObject(question);
        };
      })(this));
    }
  }
});

export default PageController;
