// Generated by CoffeeScript 1.10.0
import DS from 'ember-data';
import Ember from 'ember';
var Questionnaire;

Questionnaire = DS.Model.extend({
  advertiseLogin: DS.attr('boolean'),
  pages: DS.hasMany('page', {
    async: true
  }),
  pagesSorting: ['position'],
  pagesSorted: Ember.computed.sort('pages', 'pagesSorting'),
  hasMultiplePages: (function() {
    return this.get('pages.length') > 1;
  }).property('pages')
});

export default Questionnaire;
