// Generated by CoffeeScript 1.10.0
import DS from 'ember-data';
var QuestionOption;

QuestionOption = DS.Model.extend({
  question: DS.belongsTo('question'),
  option: DS.attr('string'),
  outputValue: DS.attr('string'),
  position: DS.attr('number')
});

export default QuestionOption;
