// Generated by CoffeeScript 1.10.0
import Ember from 'ember';
var PagesController;

PagesController = Ember.ArrayController.extend({
  questionnaire: null,
  needs: "questionnaire",
  questionnaireBinding: "controllers.questionnaire",
  itemController: 'page',
  defaultLayout: 'left',
  currentPage: null,
  actions: {
    addQuestion: function(type, purpose) {
      var question;
      question = this.store.createRecord('question', {
        page: this.get('model'),
        type: type,
        purpose: purpose,
        layout: this.get('defaultLayout')
      });
      return question.save().then((function(_this) {
        return function() {
          return _this.get('questions').addObject(question);
        };
      })(this));
    },
    createPage: function() {
      var page;
      page = this.get('store').createRecord(Page, {
        questionnaire: this.get('questionnaire.content')
      });
      page.save();
      return this.transitionToRoute('page', page);
    },
    deletePage: function(page) {
      if (confirm("Do you really want to delete the page \"" + (page.get('title')) + "\"?")) {
        page.deleteRecord();
        page.save();
        return this.transitionToRoute('questionnaire.pages', { questionnaire: this.get('questionnaire') });
      }
    }
  }
});

export default PagesController;
