// Generated by CoffeeScript 1.10.0
import Ember from 'ember';
var PagesRoute;

PagesRoute = Ember.Route.extend({
  actions: {
    setCurrentPage: function(page) {
      var pageController;
      this.transitionTo('admin.questionnaire.pages.page', page);
      pageController = this.controllerFor('admin.questionnaire.pages.page');
      return Ember.run.schedule('afterRender', pageController, pageController.scrollIntoView);
    }
  }
});

export default PagesRoute;
