name: Release

on:
  release:
    types: [published]

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Write dockerfile for release
        run: |
          echo "FROM ghcr.io/${{ github.repository }}:${{ github.sha }}" >Dockerfile
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.release.name }}
            ghcr.io/${{ github.repository }}:latest
  fly-release:
    runs-on: ubuntu-latest
    needs:
      - docker-release
    strategy:
      matrix:
        app:
          - journeysurveys
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a ${{ matrix.app }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
