// Generated by CoffeeScript 1.10.0
import Ember from 'ember';
var QuestionnaireRoute;

QuestionnaireRoute = Ember.Route.extend({
  model: function(params, transition) {
    return this.store.find('questionnaire', params.questionnaire_id);
  },
  redirect: function(model) {
    //return this.transitionTo('admin.questionnaire.pages', { questionnaire: model });
  }
});

export default QuestionnaireRoute;
